export default () => ({
    userWalletAddress:null,
    userNFT:[], 
    userRecentUnminted:[], 
    userRecentMinted:[],
    userNFTUnminted:[],
    userNFTInAuction:[],
    userNFTWonAuction:[],
    unmintedItems:[],
    userNFTMinted:[],    
    userOwnedNFT:[],
    curNFTMeta:{},
    curNFTAuctionedData:{},
    userAuctionedList:[],
    user:null,
    token:null,
});
